//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_3.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class expediente
    {
        public int idExpediente { get; set; }
        public int numExpediente { get; set; }
        public string subGrupoVictimario { get; set; }
        public int numAutopsia { get; set; }
        public string tipoMuerte { get; set; }
        public string funcion { get; set; }
        public string nombreEntidad { get; set; }
        public string intensidad { get; set; }
        public string atributo { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
