//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_3.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class lugarHecho
    {
        public int idLugar { get; set; }
        public string pais { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }
        public string barrio { get; set; }
        public string avenida { get; set; }
        public string calle { get; set; }
        public double x { get; set; }
        public double y { get; set; }
    
        public virtual hecho hecho { get; set; }
    }
}
