//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_3.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class objeto
    {
        public int idObjeto { get; set; }
        public string serie { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public string color { get; set; }
        public string descripcion { get; set; }
        public string nombreEntidad { get; set; }
        public string atributo { get; set; }
        public string observacion { get; set; }
        public Nullable<int> decomisado { get; set; }
        public Nullable<int> idTipo { get; set; }
        public int idRol { get; set; }
        public int idImagen { get; set; }
        public int idSubTipo { get; set; }
    
        public virtual imagen imagen { get; set; }
        public virtual rol rol { get; set; }
        public virtual subTipoObjeto subTipoObjeto { get; set; }
        public virtual tipoObjeto tipoObjeto { get; set; }
    }
}
