//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_3.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class policia
    {
        public int idPolicia { get; set; }
        public int placa { get; set; }
        public string caseta { get; set; }
        public string detalle { get; set; }
        public int idUnidad { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual unidad unidad { get; set; }
    }
}
