//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_3.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public int idVehiculo { get; set; }
        public string clase { get; set; }
        public string codigo { get; set; }
        public int numeroBien { get; set; }
        public System.DateTime anio { get; set; }
        public string marca { get; set; }
        public string color { get; set; }
        public string estilo { get; set; }
        public string nombreEntidad { get; set; }
        public string intensidad { get; set; }
        public string atributo { get; set; }
        public Nullable<int> poliza { get; set; }
        public Nullable<int> decomisa { get; set; }
        public string observacion { get; set; }
        public int idRol { get; set; }
        public int idImagen { get; set; }
    
        public virtual imagen imagen { get; set; }
        public virtual rol rol { get; set; }
        public virtual tipoIdVehiculo tipoIdVehiculo { get; set; }
    }
}
